// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXPE0fKtvjg5CvmxblEs447QnMe-Ew8XQ',
    appId: '1:53285296610:web:092acf52c51a04ab1f81bb',
    messagingSenderId: '53285296610',
    projectId: 'apx-pro-97f8d',
    authDomain: 'apx-pro-97f8d.firebaseapp.com',
    storageBucket: 'apx-pro-97f8d.firebasestorage.app',
    measurementId: 'G-BTPWD4MF0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWJK-WDe5wMaByD47BZZyFtuOCFMHzyK8',
    appId: '1:53285296610:android:7fc2328bbec5064d1f81bb',
    messagingSenderId: '53285296610',
    projectId: 'apx-pro-97f8d',
    storageBucket: 'apx-pro-97f8d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-aqA-yjYk6CX5JCX-6PN_FABUA9SsHj0',
    appId: '1:53285296610:ios:3167b12096fd8fe81f81bb',
    messagingSenderId: '53285296610',
    projectId: 'apx-pro-97f8d',
    storageBucket: 'apx-pro-97f8d.firebasestorage.app',
    iosBundleId: 'com.example.apxPro',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-aqA-yjYk6CX5JCX-6PN_FABUA9SsHj0',
    appId: '1:53285296610:ios:3167b12096fd8fe81f81bb',
    messagingSenderId: '53285296610',
    projectId: 'apx-pro-97f8d',
    storageBucket: 'apx-pro-97f8d.firebasestorage.app',
    iosBundleId: 'com.example.apxPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXPE0fKtvjg5CvmxblEs447QnMe-Ew8XQ',
    appId: '1:53285296610:web:c7efb9f4c19a09401f81bb',
    messagingSenderId: '53285296610',
    projectId: 'apx-pro-97f8d',
    authDomain: 'apx-pro-97f8d.firebaseapp.com',
    storageBucket: 'apx-pro-97f8d.firebasestorage.app',
    measurementId: 'G-1EJ9H98SHG',
  );
}
